In [1]:
#Fuzzy c means clustering algorithm
import numpy as np, numpy.random
import pandas as pd
from scipy.spatial import distance
k = 2
p = 2

X = pd.DataFrame([
        [1,2], 
        [3,2], 
        [5,2], 
        [1,1],
        [5,1]])
#print(X)
# To import data from disk; "C:\\MachineLearning\\Data" is the path
# where the file "fuzzyData.txt" is there
# X = pd.read_csv('C:\\MachineLearning\\Data\\fuzzyData.txt',header = None)
#print(X)


# Print the number of data and dimension 
n = len(X)
d = len(X.columns)
addZeros = np.zeros((n, 1))
X = np.append(X, addZeros, axis=1)
print("The FCM algorithm: \n")
print("The training data: \n", X)
print("\nTotal number of data: ",n)
print("Total number of features: ",d)
print("Total number of Clusters: ",k)

# Create an array of centers
#C = np.zeros((k,d+1))
C = np.array([[2.75,3,0], [3.25,0,0]])
#print(C)

# initialize the weight matrix
#weight = np.random.dirichlet(np.ones(k),size=n)
weight = np.array([[0.31, 0.69], [0.2,0.8], [0.46,0.54], [0.54, 0.46], [0.69, 0.31]])
#weight = np.array([[0.69, 0.31], [0.79, 0.21], [0.54, 0.46], [0.46, 0.54], [0.31, 0.69]])
print("\nThe initial weight: \n", np.round(weight,2))

for it in range(2): # Total number of iterations
    
    # Compute centroid
    for j in range(k):
        denoSum = sum(np.power(weight[:,j],2))
        
        sumMM =0
        for i in range(n):
            mm = np.multiply(np.power(weight[i,j],p),X[i,:])
            sumMM +=mm
        cc = sumMM/denoSum
        C[j] = np.reshape(cc,d+1)
 
    #print("\nUpdating the fuzzy pseudo partition")
    for i in range(n):
        denoSumNext = 0
        for j in range(k):
             denoSumNext += np.power(1/distance.euclidean(C[j,0:d], X[i,0:d]),1/(p-1))
        for j in range(k):
            w = np.power((1/distance.euclidean(C[j,0:d], X[i,0:d])),1/(p-1))/denoSumNext
            weight[i,j] = w  
            
print("\nThe final weights: \n", np.round(weight,2))
    
    
for i in range(n):    
    cNumber = np.where(weight[i] == np.amax(weight[i]))
    X[i,d] = cNumber[0]
    
print("\nThe data with cluster number: \n", X)

# Sum squared error calculation
SSE = 0
for j in range(k):
    for i in range(n):
        SSE += np.power(weight[i,j],p)*distance.euclidean(C[j,0:d], X[i,0:d])

print("\nSSE: ",np.round(SSE,4))

The FCM algorithm: 

The training data: 
 [[1. 2. 0.]
 [3. 2. 0.]
 [5. 2. 0.]
 [1. 1. 0.]
 [5. 1. 0.]]

Total number of data:  5
Total number of features:  2
Total number of Clusters:  2

The initial weight: 
 [[0.31 0.69]
 [0.2  0.8 ]
 [0.46 0.54]
 [0.54 0.46]
 [0.69 0.31]]

The final weights: 
 [[0.35 0.65]
 [0.42 0.58]
 [0.65 0.35]
 [0.37 0.63]
 [0.66 0.34]]

The data with cluster number: 
 [[1. 2. 1.]
 [3. 2. 1.]
 [5. 2. 0.]
 [1. 1. 1.]
 [5. 1. 0.]]

SSE:  4.1495
